# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "groups", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
  end

  create_table "members", :force => true do |t|
    t.integer  "group_id"
    t.string   "login"
    t.string   "fullname"
    t.string   "email"
    t.string   "full_name"
    t.string   "crypted_password",          :limit => 40
    t.string   "salt",                      :limit => 40
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "remember_token"
    t.datetime "remember_token_expires_at"
  end

  create_table "timetracks", :force => true do |t|
    t.datetime "created_at"
    t.integer  "member_id"
    t.date     "date"
    t.string   "description"
    t.float    "hours_spent"
  end

end
